# Generated by Django 5.0.6 on 2024-05-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('ship_date', models.DateTimeField()),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
